---
- hosts: localhost
  connection: local
  become: false
  vars:
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false
  pre_tasks:
    - name: Ensuring Homebrew Is Installed [homebrew_check]
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Stop if Homebrew is missing
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing
    
  roles:
    - homebrew