---
- name: Updating Homebrew
  homebrew:
    update_homebrew: true

- name: Upgrading Homebrew Packages
  homebrew:
    upgrade_all: true
  register: result
  
- name: Ensure Homebrew taps are tapped.
  homebrew_tap:
    name: "{{ item }}"
  loop: "{{ brew_taps }}"

- name: Installing Homebrew Packages
  homebrew:
    name: "{{ brew_packages }}"
    state: present
  register: result
    
- name: Install Cask Applications
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_cask_packages }}"
